import pandas as pd
s1=pd.read_csv("OTRec/Outputs/S1-DL_novel_predictions.csv")
print("S1 cols:",list(s1.columns)); print("rows",len(s1),"dis",s1.diseaseId.nunique(),"tgt",s1.targetId.nunique())
print("score min/med/max", s1.score.min(), s1.score.median(), s1.score.max())
print("rows with score>0.65 strict:", (s1.score>0.65).sum(), " >=0.65:", (s1.score>=0.65).sum())
print("dupes:", s1.duplicated(["diseaseId","targetId"]).sum())
g=s1.groupby("diseaseId").size()
print("per-disease mean %.2f median %.0f q25 %.0f q75 %.0f max %d ; at cap200: %d"%(g.mean(),g.median(),g.quantile(.25),g.quantile(.75),g.max(),(g==200).sum()))
vc=s1.groupby("targetSymbol")["diseaseId"].nunique().sort_values(ascending=False)
print("\ntop10 targets by #diseases:\n", vc.head(10).to_string())
nd=s1.diseaseId.nunique()
print("top1 pct of diseases: %.2f%%"%(100*vc.iloc[0]/nd))
s1["rk"]=s1.groupby("diseaseId")["score"].rank(ascending=False,method="first")
t25=s1[s1.rk<=25].groupby("targetSymbol")["diseaseId"].nunique()
print("GUCY1B2 in top25 of %d diseases (%.2f%%)"%(t25.get("GUCY1B2",0),100*t25.get("GUCY1B2",0)/nd))
print("top10 combined row share: %.2f%%"%(100*s1[s1.targetSymbol.isin(vc.head(10).index)].shape[0]/len(s1)))
print("\norphan flag:", s1.orphan.dtype, s1.groupby("orphan")["diseaseId"].nunique().to_dict())
orp=s1[s1.orphan].groupby("diseaseId").size()
print("orphan diseases %d ; >1 candidate: %d ; median %.1f"%(len(orp),(orp>1).sum(),orp.median()))
s2=pd.read_csv("OTRec/Outputs/S2-DL_novel+known_candidates.csv")
print("\nS2 rows",len(s2),"cols",list(s2.columns)[:12])
if 'source' in s2.columns: print(s2['source'].value_counts().to_dict())
